quarkus.datasource.db-kind=mysql
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/quarkus_social
quarkus.datasource.username=root
quarkus.datasource.password=root

quarkus.datasource.jdbc.drive=com.mysql.cj.jbdc.Driber

quarkus.hibernate-orm.datasource.generation=update
quarkus.hibernate-orm.log.sql=true