#Ambiente Global

quarkus.datasource.db-kind=mysql
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/quarkus_social
quarkus.datasource.username=root
quarkus.datasource.password=root

quarkus.datasource.jdbc.drive=com.mysql.cj.jbdc.Driber

quarkus.hibernate-orm.datasource.generation=update
quarkus.hibernate-orm.log.sql=true

#Ambiente de teste
%test.quarkus.datasource.db-kind=h2
%test.quarkus.datasource.username=sa
%test.quarkus.datasource.password=sa
%test.quarkus.datasource.jdbc.url=jdbc:h2:mem:quarkus_social
%test.quarkus.hibernate-orm.database.generation=drop-and-create
%test.quarkus.hibernate-orm.log.sql=true

%test.quarkus.datasource.jdbc.driver=org.h2.Driver
